version: '3.1'
services:
  snippetbox-db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: snippetbox
      MYSQL_USER: web_user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
